<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A96QGMO" ignored="19" name="contentTest" tests="9" failures="4" timestamp="18 Aug 2019 08:47:35 GMT" time="121.873" errors="0">
  <testcase name="@BeforeMethod openApplication" time="0.0" classname="com.lifeco.generic.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.lifeco.generic.BaseTest.openApplication(BaseTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod zpostcondition" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod zpostcondition -->
  <testcase name="@BeforeMethod openApplication" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod zpostcondition" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod zpostcondition -->
  <testcase name="@BeforeMethod openApplication" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod zpostcondition" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod zpostcondition -->
  <testcase name="@BeforeMethod openApplication" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod zpostcondition" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod zpostcondition -->
  <testcase name="@BeforeMethod openApplication" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod zpostcondition" time="0.0" classname="com.lifeco.generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod zpostcondition -->
  <testcase name="createNewIndividualChallenge" time="17.158" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.lifeco.tests.Content_ChallengesPage_Test.navigate(Content_ChallengesPage_Test.java:50)
at com.lifeco.tests.Content_ChallengesPage_Test.createNewIndividualChallenge(Content_ChallengesPage_Test.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createNewIndividualChallenge -->
  <testcase name="createNewCommunityChallenge" time="18.486" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.lifeco.tests.Content_ChallengesPage_Test.navigate(Content_ChallengesPage_Test.java:50)
at com.lifeco.tests.Content_ChallengesPage_Test.createNewCommunityChallenge(Content_ChallengesPage_Test.java:207)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createNewCommunityChallenge -->
  <testcase name="verifyNewCategory" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <skipped/>
  </testcase> <!-- verifyNewCategory -->
  <testcase name="creatNewCompetativeChallenge" time="18.631" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.lifeco.tests.Content_ChallengesPage_Test.navigate(Content_ChallengesPage_Test.java:50)
at com.lifeco.tests.Content_ChallengesPage_Test.creatNewCompetativeChallenge(Content_ChallengesPage_Test.java:301)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- creatNewCompetativeChallenge -->
  <testcase name="creatNewBeatMyBestChallenge" time="18.389" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.lifeco.tests.Content_ChallengesPage_Test.navigate(Content_ChallengesPage_Test.java:50)
at com.lifeco.tests.Content_ChallengesPage_Test.creatNewBeatMyBestChallenge(Content_ChallengesPage_Test.java:394)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- creatNewBeatMyBestChallenge -->
  <testcase name="verifyAddArticalFeedback" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <skipped/>
  </testcase> <!-- verifyAddArticalFeedback -->
  <testcase name="verifyAddArtical_URLLink" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <skipped/>
  </testcase> <!-- verifyAddArtical_URLLink -->
  <testcase name="verifyAddArtical_LinkToArtical" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <skipped/>
  </testcase> <!-- verifyAddArtical_LinkToArtical -->
  <testcase name="verifyAddArtical_None" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <skipped/>
  </testcase> <!-- verifyAddArtical_None -->
  <testcase name="closeChallengeCreation" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- closeChallengeCreation -->
  <testcase name="@BeforeTest intialize" time="0.0" classname="com.lifeco.generic.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest intialize -->
  <testcase name="verifyReset" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifyReset -->
  <testcase name="verifyEditArtical" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyEditArtical -->
  <testcase name="verifyImagesTabErrorMsg" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifyImagesTabErrorMsg -->
  <testcase name="verifyEditCategory" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyEditCategory -->
  <testcase name="verifyNavigationToConfigureLearningCenter" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyNavigationToConfigureLearningCenter -->
  <testcase name="verifyEditCancel" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyEditCancel -->
  <testcase name="verifyDetailsErrorMsg" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifyDetailsErrorMsg -->
  <testcase name="verifyErrorAddArtical" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyErrorAddArtical -->
  <testcase name="showChallengeRecords" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- showChallengeRecords -->
  <testcase name="noOfChallengesCreated" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- noOfChallengesCreated -->
  <testcase name="verifySheduleAvailabilityErrorMsg" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifySheduleAvailabilityErrorMsg -->
  <testcase name="verifyErrorNewCategory" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyErrorNewCategory -->
  <testcase name="verifyAddArtical_contactRequested" time="0.0" classname="com.lifeco.tests.Content_LearningCenter_Configure_Test">
    <ignored/>
  </testcase> <!-- verifyAddArtical_contactRequested -->
  <testcase name="verifyAuidenceErrorMsg" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifyAuidenceErrorMsg -->
  <testcase name="copyExistingIndividualChallenge" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- copyExistingIndividualChallenge -->
  <testcase name="verifyRulesAndStagesErrorMsg" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- verifyRulesAndStagesErrorMsg -->
  <testcase name="showChallegesDateRange" time="0.0" classname="com.lifeco.tests.Content_ChallengesPage_Test">
    <ignored/>
  </testcase> <!-- showChallegesDateRange -->
</testsuite> <!-- contentTest -->
